<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SeedMasyarkat extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nik' => '3201010101010001',
                'nama_pengadu' => 'Budi Santoso',
                'email' => 'budi@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Merdeka No. 1',
                'tgl_lahir' => '1995-04-12',
                'no_telpon' => '081234567890',
                'jenis_kelamin' => 'L',
                'pekerjaan' => 'Profesional',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => 'PT. Sinar Jaya',
                'jabatan' => 'Staff',
                'level' => 'warga',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '3201010101010002',
                'nama_pengadu' => 'Siti Aisyah',
                'email' => 'siti@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Kenangan No. 45',
                'tgl_lahir' => '1998-10-21',
                'no_telpon' => '082345678901',
                'jenis_kelamin' => 'P',
                'pekerjaan' => 'Pelajar/Mahasiswa/Akademisi',
                'kampus' => 'Universitas Maju Bersama',
                'jurusan' => 'Sistem Informasi',
                'instansi' => null,
                'jabatan' => null,
                'level' => 'warga',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '3201010101010003',
                'nama_pengadu' => 'Joko Pratama',
                'email' => 'joko@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Pantai Indah No. 78',
                'tgl_lahir' => '1990-02-05',
                'no_telpon' => '083345678900',
                'jenis_kelamin' => 'L',
                'pekerjaan' => 'Nelayan',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => null,
                'jabatan' => null,
                'level' => 'tamu',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // DATA 4 – 15 dummy random
            [
                'nik' => '3201010101010004',
                'nama_pengadu' => 'Agus Kurniawan',
                'email' => 'agus@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Melati No. 10',
                'tgl_lahir' => '1988-11-20',
                'no_telpon' => '081267890111',
                'jenis_kelamin' => 'L',
                'pekerjaan' => 'Wirasusaha',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => null,
                'jabatan' => null,
                'level' => 'warga',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '3201010101010005',
                'nama_pengadu' => 'Dewi Lestari',
                'email' => 'dewi@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Mawar No. 22',
                'tgl_lahir' => '1993-07-09',
                'no_telpon' => '081299887766',
                'jenis_kelamin' => 'P',
                'pekerjaan' => 'Profesional',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => 'PT. Makmur Sejahtera',
                'jabatan' => 'Manager',
                'level' => 'warga',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '3201010101010006',
                'nama_pengadu' => 'Rahmat Hidayat',
                'email' => 'rahmat@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Sudirman No. 3',
                'tgl_lahir' => '1996-03-03',
                'no_telpon' => '081244789000',
                'jenis_kelamin' => 'L',
                'pekerjaan' => 'Petani',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => null,
                'jabatan' => null,
                'level' => 'tamu',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '3201010101010007',
                'nama_pengadu' => 'Putri Maharani',
                'email' => 'putri@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Cendana No. 19',
                'tgl_lahir' => '2000-06-15',
                'no_telpon' => '081212345678',
                'jenis_kelamin' => 'P',
                'pekerjaan' => 'Pelajar/Mahasiswa/Akademisi',
                'kampus' => 'Universitas Teknologi Nasional',
                'jurusan' => 'Teknik Informatika',
                'instansi' => null,
                'jabatan' => null,
                'level' => 'warga',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '3201010101010008',
                'nama_pengadu' => 'Anto Gunawan',
                'email' => 'anto@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Pesona Indah Gg 3',
                'tgl_lahir' => '1985-02-22',
                'no_telpon' => '081234332221',
                'jenis_kelamin' => 'L',
                'pekerjaan' => 'Nelayan',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => null,
                'jabatan' => null,
                'level' => 'warga',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '3201010101010009',
                'nama_pengadu' => 'Maya Sari',
                'email' => 'maya@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Pasar Baru No. 88',
                'tgl_lahir' => '1999-09-09',
                'no_telpon' => '081222334455',
                'jenis_kelamin' => 'P',
                'pekerjaan' => 'Pengusaha',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => 'Toko Sari Abadi',
                'jabatan' => 'Owner',
                'level' => 'warga',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '3201010101010010',
                'nama_pengadu' => 'Fajar Nugraha',
                'email' => 'fajar@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Jl. Garuda No. 17',
                'tgl_lahir' => '1994-12-12',
                'no_telpon' => '085678901234',
                'jenis_kelamin' => 'L',
                'pekerjaan' => 'Profesional',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => 'PT. Global Tech',
                'jabatan' => 'Operator',
                'level' => 'warga',
                'created_at' => date('Y-m-d H:i:s'),
            ],
        ];

        // TOTAL 10, SEKARANG TAMBAHKAN 5 LAGI
        for ($i = 11; $i <= 15; $i++) {
            $data[] = [
                'nik' => '32010101010100' . $i,
                'nama_pengadu' => 'User Dummy ' . $i,
                'email' => 'dummy' . $i . '@example.com',
                'password' => password_hash('password', PASSWORD_DEFAULT),
                'alamat' => 'Alamat Dummy ' . $i,
                'tgl_lahir' => '1990-01-01',
                'no_telpon' => '08120000' . $i,
                'jenis_kelamin' => $i % 2 == 0 ? 'P' : 'L',
                'pekerjaan' => 'Lainnya',
                'kampus' => null,
                'jurusan' => null,
                'instansi' => null,
                'jabatan' => null,
                'level' => 'tamu',
                'created_at' => date('Y-m-d H:i:s'),
            ];
        }

        $this->db->table('masyarakat')->insertBatch($data);
    }
}
